version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: laravel_php
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    ports:
      - "9000:9000"
    networks:
      laravel_network:
        aliases:
          - hyperviewer.com

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      laravel_network:
        aliases:
          - hyperviewer.com

  sqlite:
    image: nouchka/sqlite3
    container_name: laravel_sqlite
    command: ["sqlite3", "/var/db/laravel.sqlite"]
    volumes:
      - ./app/database:/var/db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"

